project:
  type: website
  output-dir: docs

website:
  title: "AAI-Akid.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: hobbies.qmd
        text: Hobbies

format:
  html:
    theme: cosmo
    css: styles.css



