---
title: "Internship Project"
---

## Internship Project

During my internship in Year 3 of my diploma, I worked as a researcher at the NUS-Singtel Cyber Security R&D Lab. My team and I were tasked with developing an AI model to detect malware and cyber threats in network traffic. We were supervised by [Dr. Vinay Sachidananda](http://www.vinaysachi.com/index.html){target="_blank" rel="noopener"}, and the results of our research were published in a paper titled *"A novel approach for detecting vulnerable IoT devices connected behind a home NAT"*.

### Abstract taken from research paper
Telecommunication service providers (telcos) are exposed to cyber-attacks executed by compromised IoT
devices connected to their customers’ networks. Such attacks might have severe effects on the attack
target, as well as the telcos themselves. To mitigate those risks, we propose a machine learning-based
method that can detect specific vulnerable IoT device models connected behind a domestic NAT, thereby
identifying home networks that pose a risk to the telcos infrastructure and service availability. To evaluate
our method, we collected a large quantity of network traffic data from various commercial IoT devices in
our lab and compared several classification algorithms. We found that (a) the LGBM algorithm produces
excellent detection results, and (b) our flow-based method is robust and can handle situations for which
existing methods used to identify devices behind a NAT are unable to fully address, e.g., encrypted, nonTCP or non-DNS traffic. To promote future research in this domain we share our novel labeled benchmark
dataset.